### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by kopiro** [appcelerator/hyperloop#401]
```
 CXX(target) Release/obj.target/zipper/src/_zipper.o
In file included from ../src/_zipper.cc:9:
../src/zipper.hpp:25:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments &args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/flavio.destefano/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/_zipper.cc:9:
../src/zipper.hpp:28:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> addFile(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/flavio.destefano/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/_zipper.cc:9:
../src/zipper.hpp:29:26: error: unknown type name 'uv_work_t'
    static void _AddFile(uv_work_t *req);
                         ^
../src/zipper.hpp:30:31: error: unknown type name 'uv_work_t'
    static void _AfterAddFile(uv_work_t *req);
                              ^
../src/_zipper.cc:22:25: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("version"), String::New("0.0.1"));
                ~~~~~~~~^
../src/_zipper.cc:22:55: error: no member named 'New' in 'v8::String'
    target->Set(String::NewSymbol("version"), String::New("0.0.1"));
                                              ~~~~~~~~^
../src/_zipper.cc:25:42: error: too few arguments to function call, single argument 'isolate' was not specified
    Local<Object> versions = Object::New();
                             ~~~~~~~~~~~ ^
/Users/flavio.destefano/.node-gyp/0.12.7/deps/v8/include/v8.h:2388:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
../src/_zipper.cc:26:27: error: no member named 'NewSymbol' in 'v8::String'
    versions->Set(String::NewSymbol("node"), String::New(NODE_VERSION+1));
                  ~~~~~~~~^
../src/_zipper.cc:26:54: error: no member named 'New' in 'v8::String'
    versions->Set(String::NewSymbol("node"), String::New(NODE_VERSION+1));
                                             ~~~~~~~~^
../src/_zipper.cc:27:27: error: no member named 'NewSymbol' in 'v8::String'
    versions->Set(String::NewSymbol("v8"), String::New(V8::GetVersion()));
                  ~~~~~~~~^
../src/_zipper.cc:27:52: error: no member named 'New' in 'v8::String'
    versions->Set(String::NewSymbol("v8"), String::New(V8::GetVersion()));
                                           ~~~~~~~~^
../src/_zipper.cc:28:25: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("versions"), versions);
                ~~~~~~~~^
12 errors generated.
make[1]: *** [Release/obj.target/zipper/src/_zipper.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/flavio.destefano/Repos/hyperloop/node_modules/zipper
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
make: *** [lib/_zipper.node] Error 1
npm WARN optional dep failed, continuing zipper@0.3.0
```

**Comment by coderlongs** [comment]
me too. 
Anybody solve this problem?
