### ISSUE TITLE
Error when launching ios example

### ISSUE THREAD

**Issue by Martin1982** [appcelerator/hyperloop#402]
When I try the Spritekit example NodeJS returns an error:

```shell
➜  hyperloop git:(master) hyperloop launch --src="examples/ios/spritekit"
[INFO]  Generating system metabase will take up to a minute (or greater) depending on your environment. This file will be cached and will execute faster on subsequent builds.
  ◟ Generating system metabase


/Users/martin/Documents/code/hyperloop/lib/clangparser.js:1394
				m = intf.methods,
				        ^
TypeError: Cannot read property 'methods' of undefined
    at /Users/martin/Documents/code/hyperloop/lib/clangparser.js:1394:13
    at Array.forEach (native)
    at astToJSON (/Users/martin/Documents/code/hyperloop/lib/clangparser.js:1390:13)
    at Node.toJSON (/Users/martin/Documents/code/hyperloop/lib/clangparser.js:1316:10)
    at /Users/martin/Documents/code/hyperloop/lib/ios/metabase.js:102:23
    at LineStream.finish (/Users/martin/Documents/code/hyperloop/lib/clangparser.js:1549:5)
    at LineStream.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)
```

OS X Version: 10.10.5
XCode Version: 7.0 (7A220)
Node Version: v0.10.13
Hyperloop Version: 0.1.3

**Comment by sobytes** [comment]
Same issue.

~~~
/usr/local/lib/node_modules/hyperloop/lib/clangparser.js:1394
				m = intf.methods,
				        ^

TypeError: Cannot read property 'methods' of undefined
    at /usr/local/lib/node_modules/hyperloop/lib/clangparser.js:1394:13
    at Array.forEach (native)
    at astToJSON (/usr/local/lib/node_modules/hyperloop/lib/clangparser.js:1390:13)
    at Node.toJSON (/usr/local/lib/node_modules/hyperloop/lib/clangparser.js:1316:10)
    at /usr/local/lib/node_modules/hyperloop/lib/ios/metabase.js:102:23
    at LineStream.finish (/usr/local/lib/node_modules/hyperloop/lib/clangparser.js:1549:5)
    at emitNone (events.js:72:20)
    at LineStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
~~~

**Comment by jhaynie** [comment]
this project is no longer maintained and has moved to a next generation version of Hyperloop which is available from http://labs.appcelerator.com

we will update the README and the information.

**Comment by sobytes** [comment]
Ok thanks @jhaynie

**Comment by sobytes** [comment]
@jhaynie quick question i can run the hyperloop example application in the simulator fine but not on the device is this because it is a pre release?

~~~
[INFO] :   Generating metabase for swift MyFramework /Users/sobytes/Documents/Appcelerator_Studio_Workspace/current/src/MySwift.swift
[ERROR] :  An error occurred during build after 9s 511ms
[ERROR] :  Swift file at /Users/sobytes/Documents/Appcelerator_Studio_Workspace/current/src/MySwift.swift has compiler problems. Please check to make sure it compiles OK.
2015-12-01T17:40:27.390Z | TRACE  | titanium exited with exit code 1
2015-12-01T17:40:27.392Z | ERROR  | Error: ti run exited with error code 1
~~~

**Comment by jhaynie** [comment]
yes it shouldn't work just yet on simulator if you're using the example app since the example app only had a GUID for simulator. however, it looks like you're getting a swift exception when compiling. so, it works on simulator though?  what verison of Xcode and iOS SDK are you using?

**Comment by sobytes** [comment]
Hi @jhaynie,

I setup my own sample app here. https://bitbucket.org/SoBytes/appcelerator-hyperloop-example-app/src 

I am using xcode version 7.1.1
And Appc SDK 5.2.0.v20151201075557

Thanks
